name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  tests:
    runs-on: ubuntu-latest 
    steps:
      - name: Hacer checkout del código
        uses: actions/checkout@v4 

      - name: Instalar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: pdo, pdo_mysql

      - name: Instalar dependencias
        run: composer install --prefer-dist

      - name: Ejecutamos tests
        run: php vendor/bin/phpunit

  construir:
    runs-on: ubuntu-latest
    steps:
      - name: Hacer checkout del código
        uses: actions/checkout@v4

      - name: Configurar QEMU
        uses: docker/setup-qemu-action@v3

      - name: Configurar Buildx
        uses: docker/setup-buildx-action@v3

      - name: Loguearse en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Construir y subir la imagen multiplataforma
        uses: docker/build-push-action@v6.13.0
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USER }}/calculadora:latest
            ${{ secrets.DOCKER_USER }}/calculadora:${{ github.sha }}
