name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  construir:
    runs-on: ubuntu-latest
    steps:
      - name: Hacer checkout del código
        uses: actions/checkout@v4

      - name: Configurar QEMU
        uses: docker/setup-qemu-action@v3

      - name: Configurar Buildx
        uses: docker/setup-buildx-action@v3

      - name: Loguearse en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Construir y subir la imagen
        uses: docker/build-push-action@v6.13.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/calculadora:latest
