name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  construir:
    runs-on: ubuntu-latest
    steps:
      - name: Hacer checkout del código
        uses: actions/checkout@v4

      - name: Loguearse en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Construir la imagen de Docker
        run: docker build . --file Dockerfile --tag camilotaba/calculadora:latest

      - name: Subir la imagen a Docker Hub
        run: docker push ${{ secrets.DOCKER_USER }}/calculadora:latest
