name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Hacer checkout
        uses: actions/checkout@v4

      - name: Loguearse en Docker
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Construyendo la imagen
        run: docker build . --file Dockerfile --tag camilotaba/calculadora:latest

      - name: Subiendo imagen
        run: docker push camilotaba/calculadora:latest
